### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by telegrambotdev** [mrcentimetre/gpytranslator-bot#11]
Getting this error,when send `/start` command to the bot . How to fix it ? please check the log

https://paste.ubuntu.com/p/zdYZnFB4sn/

![IMG_20210307_080202_933](https://user-images.githubusercontent.com/20116017/110227165-71802480-7f1b-11eb-8cb4-a8b9e07b109b.jpg)

**Comment by iiiiii1wepfj** [comment]
fixed, thanks
