### ISSUE TITLE
need feature

### ISSUE THREAD

**Issue by telegrambotdev** [mrcentimetre/gpytranslator-bot#15]
can you add an option like , sentence should convert if we reply like `/tr en` in private chat too

i saw this option groups..can you add this feature in private chat too ? then we can easily translate forwarded msgs too.now i have to copy the whole test..if you added this we can translate to any languages easily,instead of changing default language in the private chat.

**Comment by iiiiii1wepfj** [comment]
try /tr (language) (text) in private chat

**Comment by telegrambotdev** [comment]
> try /tr (language) (text) in private chat

yup i saw that..but i wish that reply translation feature in private chat too.thats so good feature

**Comment by iiiiii1wepfj** [comment]
send pr if you want

**Comment by telegrambotdev** [comment]
let me check....before that if you got an idea add that feature too. thank you

**Comment by iiiiii1wepfj** [comment]
if message.reply_to_message:
 ...
else:
 ...

**Comment by telegrambotdev** [comment]
> if message.reply_to_message:
> ...
> else:
> ...

can you say which line i should edit ? and can you say the exact command i have to  add ?

**Comment by iiiiii1wepfj** [comment]
if you know python you know
