### ISSUE TITLE
Error Gpy Translator

### ISSUE THREAD

**Issue by fermani10** [mrcentimetre/gpytranslator-bot#28]
How is this error solved? the bot won't let me translate anything

Expecting value: line 1 column 1 (char 0)

**Comment by fermani10** [comment]
The error from what I found out is that google banned my ip, is there any way to solve this from the code?

**Comment by fermani10** [comment]
How is this error solved? the bot won't let me translate anything

Expecting value: line 1 column 1 (char 0)

**Comment by rojserbest** [comment]
lol

**Comment by rojserbest** [comment]
I'm closing this shittissue
