### ISSUE TITLE
Ban Google Api

### ISSUE THREAD

**Issue by fermani10** [mrcentimetre/gpytranslator-bot#29]
Hi! How are you? I have a solution for the Ban of Google API

I need to contact you to improve the library.

**Comment by iiiiii1wepfj** [comment]
what?

**Comment by fermani10** [comment]
I want to collaborate to repair the error that happens with Google.
[IMG_20210522_040514_479.jpg](https://user-images.githubusercontent.com/31140793/119217789-03c3ad80-bab3-11eb-8bd2-be8f97d643ca.jpg)

**Comment by iiiiii1wepfj** [comment]
just send a pull request
