### ISSUE TITLE
Remote Postgresql usage

### ISSUE THREAD

**Issue by rsoorajs** [mrcentimetre/gpytranslator-bot#37]
Can i use remote postgreql url in config.py to store the data ? Does it work ? or need exact mysql url?

**Comment by rsoorajs** [comment]
Which database urls it will support ?

**Comment by rojserbest** [comment]
@rsoorajs idk

**Comment by iiiiii1wepfj** [comment]
@rsoorajs what?

**Comment by rsoorajs** [comment]
I mean storing our preffered language in a database,right ? can i use postgres for that ?

**Comment by iiiiii1wepfj** [comment]
@rsoorajs yes, i use this in the main bot

**Comment by iiiiii1wepfj** [comment]
@rsoorajs very recommended

**Comment by rsoorajs** [comment]
> @rsoorajs very recommended

Thanks alot
